version: '2'
volumes:
  settings:
  sense-data: 
services:
  kiosk:
    restart: always
    network_mode: host
    build: ./kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  fbcp:
    image: balenablocks/fbcp
    network_mode: host
    privileged: true
  influxdb:
    restart: always
    build: ./influxdb
    ports:
      - 8086:8086
    volumes:
      - 'sense-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'HOME_DASHBOARD_UID=balenaSense'
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
  telegraf:
    build: ./telegraf
    restart: always
    cap_add:
      - SYS_ADMIN
  mqtt:
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always